name: wechat
description: A WeChat Clone Application

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  firebase_app_check: ^0.2.1+6
  emoji_picker_flutter: ^1.6.3
  firebase_messaging: ^14.7.6
  http: ^1.1.0
  flutter_notification_channel: ^2.0.0
  image_gallery_saver: ^2.0.3
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "images/icon.png"   
#  min_sdk_android: 21 
#  remove_alpha_ios: true
  

flutter:
  
  uses-material-design: true

  assets:
    - "images/icon.png"
    - "images/google.png"
    - "images/gallery.png"
    - "images/photo.png"