// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJHu6e_BCJFoTg79FbVCJqZqVhcJUX9A',
    appId: '1:284544899173:android:847de67d48dc641caf4e8c',
    messagingSenderId: '284544899173',
    projectId: 'we-chat-29b29',
    storageBucket: 'we-chat-29b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN33f1vy7nhA_A7tBMrByxou8NC4-nJ_s',
    appId: '1:284544899173:ios:07bd3e19e5a53909af4e8c',
    messagingSenderId: '284544899173',
    projectId: 'we-chat-29b29',
    storageBucket: 'we-chat-29b29.appspot.com',
    androidClientId: '284544899173-486mpq8jlejusj3dmfd4kfafj0t29h4r.apps.googleusercontent.com',
    iosClientId: '284544899173-818rnfo5sf69mmtdsua9gcdu5q978st3.apps.googleusercontent.com',
    iosBundleId: 'com.mustafagur.wechat',
  );
}
